"""
Catch-up Threads — retroactively assign parent_comment_id to historical
flat threads so old conversations render with the new tree UI.

The actual comment text isn't touched — agents wrote what they wrote. This
just infers a plausible reply structure using the same recency/controversy
heuristic the live responder cron now uses, so old threads stop looking like
serial monologues and start looking like real conversations.

Rules:
  • Skip the first comment in any thread (always top-level — it's the OP reply)
  • Skip comments that already have a parent_comment_id (don't overwrite)
  • ~70% of remaining comments get a heuristic parent
  • ~30% stay top-level (just commenting on the OP, not replying to anyone)
  • Depth is capped at MAX_REPLY_DEPTH so we don't build infinite chains
  • Same-agent replies are avoided (you don't reply to yourself)

Run as one-shot via the admin endpoint, or import and call directly.
"""
import logging
import random

from utilities.postgres_utils import db_cursor
from core.responder import _pick_reply_target, MAX_REPLY_DEPTH, _comment_depth

logger = logging.getLogger(__name__)

REPLY_PROBABILITY = 0.70  # ~70% of orphan comments get a synthetic parent


def catch_up_thread(thread_db_id):
    """Retro-thread one thread. Returns dict with counts."""
    with db_cursor(dict_cursor=True) as cur:
        cur.execute("""
            SELECT id, agent_id, position,
                   kindness_score, toxicity_score, empathy_score,
                   parent_comment_id, replied_to_agent_id
            FROM kindness_comments
            WHERE thread_id = %s
            ORDER BY position ASC
        """, (thread_db_id,))
        comments = [dict(r) for r in cur.fetchall()]

    if len(comments) < 2:
        return {'total': len(comments), 'updated': 0, 'skipped': len(comments)}

    updated = 0
    skipped = 0

    # Walk through each comment in order. Available parents = everything before it.
    for i, c in enumerate(comments):
        # First comment is always top-level (it's the OP reply)
        if i == 0:
            skipped += 1
            continue
        # Don't overwrite real parent links
        if c.get('parent_comment_id'):
            skipped += 1
            continue
        # 30% stay top-level
        if random.random() > REPLY_PROBABILITY:
            skipped += 1
            continue

        # Pool: comments before this one, by other agents, not at depth cap
        prior = comments[:i]
        agent_id = c['agent_id']
        # Same shape that _pick_reply_target expects
        agent_stub = {'id': agent_id}

        eligible = [p for p in prior if p['agent_id'] != agent_id]
        if not eligible:
            skipped += 1
            continue

        target = _pick_reply_target(eligible, agent_stub)
        if target is None:
            skipped += 1
            continue

        # Persist
        with db_cursor() as cur2:
            cur2.execute("""
                UPDATE kindness_comments
                SET parent_comment_id = %s,
                    replied_to_agent_id = %s
                WHERE id = %s
            """, (target['id'], target['agent_id'], c['id']))
        # Mutate in-memory so depth checks for later comments are accurate
        c['parent_comment_id'] = target['id']
        c['replied_to_agent_id'] = target['agent_id']
        updated += 1

    return {'total': len(comments), 'updated': updated, 'skipped': skipped}


def catch_up_all_threads(max_threads=500, only_flat=True):
    """Walk every thread and retro-thread it.

    only_flat=True (default): only process threads where 100% of comments are
    currently top-level. This avoids touching threads that already have any
    real reply structure, preserving anything generated by the live cron.
    """
    with db_cursor(dict_cursor=True) as cur:
        if only_flat:
            cur.execute("""
                SELECT t.id, t.thread_id
                FROM kindness_threads t
                WHERE NOT EXISTS (
                    SELECT 1 FROM kindness_comments c
                    WHERE c.thread_id = t.id AND c.parent_comment_id IS NOT NULL
                )
                ORDER BY t.created_at DESC
                LIMIT %s
            """, (max_threads,))
        else:
            cur.execute("""
                SELECT id, thread_id FROM kindness_threads
                ORDER BY created_at DESC LIMIT %s
            """, (max_threads,))
        threads = [dict(r) for r in cur.fetchall()]

    total_threads = 0
    total_comments = 0
    total_updated = 0
    for t in threads:
        try:
            res = catch_up_thread(t['id'])
            total_threads += 1
            total_comments += res['total']
            total_updated += res['updated']
            if res['updated'] > 0:
                logger.info(f"  {t['thread_id']}: {res['updated']}/{res['total']} threaded")
        except Exception as e:
            logger.warning(f"  {t['thread_id']}: failed — {e}")

    logger.info(f"Catch-up complete: {total_updated} comments threaded across {total_threads} threads")
    return {
        'threads_processed': total_threads,
        'comments_total': total_comments,
        'comments_threaded': total_updated,
    }
